### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Metzlmane** [Sylphe88/PromVIEW#1]
Hi,

thanks a lot for this. It is really easy to use. 
I tried to add a lot more gauges but at some point .. I always get this error and then it's impossible to get rid of it...
![Clipboard Image](https://user-images.githubusercontent.com/9552092/106365925-f4202d80-6338-11eb-8a50-ec0abbb28ad1.jpg)
A simple dash "-" in the metrics name caused this.

So maybe I just didn't see some rules, but avoiding any special characters solves the problem.

Maybe sth. like removing all non character names when creating a gauge would be nice.

**Comment by Sylphe88** [comment]
Hi @Metzlmane,

You are correct in that the metric naming is strict and [defined by Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). You should make sure your metrics are named accordingly. The Metrics.lvlib:Metric.lvclass:Validate Name.vi makes sure this naming is applied in PromVIEW and throw error 9803.

I'll still leave this issue open until an error file is added to the library so the LV error dialog is meaningful for users.

**Comment by Sylphe88** [comment]
The custom error file was copied at the wrong place, it's now fixed with 1.1.0!
