### ISSUE TITLE
Request: Label example

### ISSUE THREAD

**Issue by Metzlmane** [Sylphe88/PromVIEW#2]
Could you please add a simple example, how to create one metric with some labels?
I tried to create a gauge metric with "channel" "A/B/C" and so on.. but several approaches failed during the registry.

It would be much aprreciated

I hope this is not totally wrong:
![image](https://user-images.githubusercontent.com/9552092/112470148-99201b00-8d6a-11eb-8157-8f71a8fd70f7.png)

**Comment by Metzlmane** [comment]
To specify the problem:
i tried to get something like
instrument_pressure_mbar{channel="A"} 12
instrument_pressure_mbar{channel="B"} 0.1

My understanding ist, that this is not possible due to the "Register Metric" VI, since the metric is added as key to the Map.
This is either not possible due to duplicate name of the metric, or replaces the first one.

**Comment by Sylphe88** [comment]
You're absolutely right, it was a poor design decision to use maps to store labels are their cardinality is meant to be > 1. I'll patch this as soon as I get a chance (this weekend without any guarantee though!)

**Comment by Metzlmane** [comment]
Any news? 
If you are too busy I could also do it, or at least give it a try.

**Comment by Sylphe88** [comment]
I've started redesigning how metrics are structured, I'll have more time this week to work on it and finish it hopefully ;)

**Comment by Sylphe88** [comment]
All merged with modifications (as well as other fixes and enhancements). The sample projects in LabVIEW 20xx\examples\TheLabVIEWLab both show how to use labels now for guidance.
